semester: 2026S

output:
   base_dir: output/
   data_dir: data/
   courses_dir: courses/

crawl:
   sleep_between_requests: 60         # seconds between requests
   resume: true                       # pick up from existing state.json if present
   url_curricula: https://tiss.tuwien.ac.at/curriculum/studyCodes.xhtml # url containing all curricula
   url_base_curricula: https://tiss.tuwien.ac.at/curriculum/public/curriculumSemester.xhtml
   url_course: https://tiss.tuwien.ac.at/course/courseDetails.xhtml

logging:
   level: INFO
   file: output/logs/crawler.log
