semester: 2025S

output:
   base_dir: output/

crawl:
   sleep_between_requests: 30         # seconds between requests
   resume: true                       # pick up from existing state.json if present
   url_bootstrap: https://tiss.tuwien.ac.at/curriculum/studyCodes.xhtml # url to bootrap the session from

logging:
   level: INFO
   file: output/logs/crawler.log
