from pathlib import Path
import sys
import yaml
import logging
import state


def _load_config(config_file: str) -> dict:
	with open(config_file) as f:
		return yaml.safe_load(f)


def _escape(value: str) -> str:
	"""Escape single quotes for MySQL."""
	return value.replace("'", "\\'")


def _build_unique_id(entry: dict) -> str:
	return (
		entry["subsemester"]
		+ entry["semester"]
		+ entry["subprogram_title_de"]
		+ entry["academic_program_de"]
	)


def export_study_programs(dict_studyprograms: dict, output_path: Path) -> None:
	lines = []
	lines.append("-- Study programs export")
	lines.append("-- Generated by export.py\n")

	for key, entry in dict_studyprograms.items():
		unique_id      = _escape(_build_unique_id(entry))
		course_numbers = _escape("|".join(entry.get("course_numbers", [])))
		semester       = _escape(entry.get("semester", ""))
		subsemester    = _escape(entry.get("subsemester", ""))
		subprogram_de  = _escape(entry.get("subprogram_title_de", ""))
		subprogram_en  = _escape(entry.get("subprogram_title_en", ""))
		academic_de    = _escape(entry.get("academic_program_de", ""))
		academic_en    = _escape(entry.get("academic_program_en", ""))
		program_code   = _escape(entry.get("program_code", ""))

		sql = (
			f"INSERT IGNORE INTO `overview` "
			f"(`unique_id`, `course_numbers`, `semester`, `subsemester`, "
			f"`subprogram_title_de`, `subprogram_title_en`, "
			f"`academic_program_de`, `academic_program_en`, `program_code`) "
			f"VALUES ("
			f"'{unique_id}', '{course_numbers}', '{semester}', '{subsemester}', "
			f"'{subprogram_de}', '{subprogram_en}', "
			f"'{academic_de}', '{academic_en}', '{program_code}'"
			f");"
		)
		lines.append(sql)

	output_path.parent.mkdir(parents=True, exist_ok=True)
	output_path.write_text("\n".join(lines), encoding="utf-8")
	logging.getLogger(__name__).info(f"Wrote {len(dict_studyprograms)} rows to {output_path}")


# Map lang -> {field_name: json_key}
_FIELD_KEYS = {
    "en": {
        "properties":       "properties",
        "more_info":        "additional information",
        "subj_of_course":   "subject of course",
        "methods":          "teaching methods",
        "exam_mode":        "mode of examination",
        "exam_modalities":  "examination modalities",
        "course_reg":       "course registration",
        "literatur":        "literature",
        "prev_knowledge":   "previous knowledge",
        "preced_courses":   "preceding courses",
        "lecturers":        "lecturers",
        "language":         "language",
        "institute":        "institute",
        "group_dates":      "groups and dates",
        "exams":            "exams",
        "group_reg":        "group registration",
        "course_dates":     "course dates",
        "curricula":        "curricula",
        "aim_of_course":    "aim of course",
        "learning_outcome": "learning outcomes",
    },
    "de": {
        "properties":       "merkmale",
        "more_info":        "weitere informationen",
        "subj_of_course":   "inhalt der lehrveranstaltung",
        "methods":          "methoden",
        "exam_mode":        "prüfungsmodus",
        "exam_modalities":  "leistungsnachweis",
        "course_reg":       "lva-anmeldung",
        "literatur":        "literatur",
        "prev_knowledge":   "vorkenntnisse",
        "preced_courses":   "vorausgehende lehrveranstaltungen",
        "lecturers":        "vortragende personen",
        "language":         "sprache",
        "institute":        "institut",
        "group_dates":      "gruppentermine",
        "exams":            "prüfungen",
        "group_reg":        "gruppen-anmeldung",
        "course_dates":     "lva termine",
        "curricula":        "curricula",
        "aim_of_course":    "ziele der lehrveranstaltung",
        "learning_outcome": "lernergebnisse",
    },
}


def _extract_lecturers(lecturer_entry: str):
	print(f"lecturer_entry: {lecturer_entry}")


def _extract_curricula(curricula_entry: str):
	print(f"curricula_entry: {curricula_entry}")


def _courses_process_lang(
	entry: dict,
	page_fetch_lang: str,
	table_name: str
) -> tuple[int, str]:
	"""
	Indices for de/en language dicts differ! -> select using "page_fetch_lang"
	"""
	lang_entry = entry[page_fetch_lang]
	keys = _FIELD_KEYS[page_fetch_lang]

	non_empty_count = 0
	def get(field):
		nonlocal non_empty_count
		value = lang_entry.get(keys[field]) or ""
		if value:
			non_empty_count += 1
		return value

	course_number    = lang_entry.get("course_number", "")
	course_title     = lang_entry.get("course_title", "")
	semester         = lang_entry.get("course_semester", "")
	course_type      = lang_entry.get("course_type", "")
	course_sws       = lang_entry.get("course_hours", "")
	course_ECTS      = lang_entry.get("course_ECTS", "")
	additional_info  = lang_entry.get("course_add_info", "") or ""

	properties       = get("properties")
	more_info        = get("more_info")
	subj_of_course   = get("subj_of_course")
	methods          = get("methods")
	examination_mode = get("exam_mode")
	exam_modalities  = get("exam_modalities")
	course_reg       = get("course_reg")
	literatur        = get("literatur")
	prev_knowledge   = get("prev_knowledge")
	preced_courses   = get("preced_courses")
	lecturers        = _extract_lecturers(get("lecturers"))
	language         = get("language")
	institute        = get("institute")
	group_dates      = get("group_dates")
	exams            = get("exams")
	group_reg        = get("group_reg")
	course_dates     = get("course_dates")
	curricula        = str(_extract_curricula(get("curricula")))
	aim_of_course    = get("aim_of_course")
	learning_outcome = get("learning_outcome")

	sql = (
		f"INSERT IGNORE INTO `{table_name}` "
		f"(`page_fetch_lang`, `course_number`, `course_title`, "
		f"`semester`, `type`, `sws`, `ECTS`, `add_info`, "
		f"`Merkmale`, `Weitere Informationen`, `Inhalt der Lehrveranstaltung`, "
		f"`Methoden`, `Prüfungsmodus`, `Leistungsnachweis`, `LVA_Anmeldung`, `Literatur`, "
		f"`Vorkenntnisse`, `Vorausgehende Lehrveranstaltungen`, `Vortragende Personen`, "
		f"`Sprache`, `Institut`, `Gruppentermine`, `Prüfungen`, `Gruppen_Anmeldung`, "
		f"`LVA Termine`, `Curricula`, `Ziele der Lehrveranstaltung`, `Lernergebnisse`) "
		f"VALUES ("
		f"'{page_fetch_lang}', '{course_number}', '{course_title}', '{semester}', "
		f"'{course_type}', '{course_sws}', '{course_ECTS}', '{additional_info}', "
		f"'{properties}', '{more_info}', '{subj_of_course}', '{methods}',"
		f"'{examination_mode}', '{exam_modalities}', '{course_reg}',"
		f"'{literatur}', '{prev_knowledge}', '{preced_courses}', '{lecturers}',"
		f"'{language}', '{institute}', '{group_dates}', '{exams}',"
		f"'{group_reg}', '{course_dates}', '{curricula}', '{aim_of_course}',"
		f"'{learning_outcome}'"
		f");"
	)

	return non_empty_count, sql


def export_courses(
	dict_courses: dict,
	table_name  : str,
	output_path : Path
) -> None:
	lines = []
	lines.append("-- Courses export")
	lines.append("-- Generated by export.py\n")

	i = 0

	for course_number, entry in dict_courses.items():

		# make sure both languages properly extracted
		if not ("en" or "de") in entry:
			log.error(f"missing language (de/en) in course '{course_number}'")
			continue

		# process german language of dict
		page_fetch_lang  = "de"
		non_empty_count_de, sql = _courses_process_lang(entry, page_fetch_lang, table_name)
		lines.append(sql)

		# process english language of dict
		page_fetch_lang  = "en"
		non_empty_count_en, sql = _courses_process_lang(entry, page_fetch_lang, table_name)
		lines.append(sql)

		print(sql)

		# amount of "en" and "de" non-emmpty values should be the same
		if non_empty_count_de != non_empty_count_en:
			log.error(
				f"Amount of parameters ('de'/'en') mismatch: "
				f"{non_empty_count_de}/{non_empty_count_en}"
			)

		print(f"non_empty_count_de: {non_empty_count_de}, non_empty_count_en: {non_empty_count_en}")
		sys.exit()

		i = i + 1

	print(i)

"""
	course_number    = entry[page_fetch_lang].get("course_number", None)
	course_title     = entry[page_fetch_lang].get("course_title", None)
	semester         = entry[page_fetch_lang].get("semester", None)
	course_type      = entry[page_fetch_lang].get("course_type", None)
	course_sws       = entry[page_fetch_lang].get("course_hours", None)
	course_ECTS      = entry[page_fetch_lang].get("course_ECTS", None)
	additional_info  = entry[page_fetch_lang].get("course_add_info", None)
	properties       = entry[page_fetch_lang].get("properties", None)             # de: merkmale
	more_info        = entry[page_fetch_lang].get("additional information", None) # de: Weitere Informationen
	subj_of_course   = entry[page_fetch_lang].get("subject of course", None)      # de: "inhalt der lehrveranstaltung"
	methods          = entry[page_fetch_lang].get("teaching methods", None)       # de: "methoden"
	examination_mode = entry[page_fetch_lang].get("mode of examination", None)    # de: "Prüfungsmodus"
	exam_modalities  = entry[page_fetch_lang].get("examination modalities", None) # de: "leistungsnachweis"
	course_reg       = entry[page_fetch_lang].get("course registration", None)    # de: "lva-anmeldung"
	literatur        = entry[page_fetch_lang].get("literatur", None)              # de: "literatur"
	prev_knowledge   = entry[page_fetch_lang].get("previous knowledge", None)     # de: "vorkenntnisse"
	preced_courses   = entry[page_fetch_lang].get("preceding courses", None)      # de: "vorausgehende lehrveranstaltungen"
	lecturers        = entry[page_fetch_lang].get("lecturers", None)              # de: "vortragende personen"
	language         = entry[page_fetch_lang].get("language", None)               # de: "sprache"
	institute        = entry[page_fetch_lang].get("institute", None)              # de: institut"
	groups_and_dates = entry[page_fetch_lang].get("groups and dates", None)       # de: "gruppen & termine"
	exams            = entry[page_fetch_lang].get("exams", None)                  # de: "prüfungen"
	group_reg        = entry[page_fetch_lang].get("group registration", None)     # de: "gruppen-anmeldung"
	course_dates     = entry[page_fetch_lang].get("course dates", None)           # de: "lva termine"
	curricula        = entry[page_fetch_lang].get("curricula", None)              # de: "curricula"
	aim_of_course    = entry[page_fetch_lang].get("aim of course", None)          # de: "Ziele der Lehrveranstaltung"
	learning_outcome = entry[page_fetch_lang].get("learning outcomes", None)      # de: "lernergebnisse"

	sql = (
		f"INSERT IGNORE INTO `{table_name}` "
		f"(`page_fetch_lang`, `course_number`, `course_title`, "
		f"`semester`, `type`, `sws`, `ECTS`, `add_info`, "
		f"`Merkmale`, `Weitere Informationen`, `Inhalt der Lehrveranstaltung`, "
		f"`Methoden`, `Prüfungsmodus`, `Leistungsnachweis`, `LVA_Anmeldung`, `Literatur`, "
		f"`Vorkenntnisse`, `Vorausgehende Lehrveranstaltungen`, `Vortragende Personen`, "
		f"`Sprache`, `Institut`, `Gruppentermine`, `Prüfungen`, `Gruppen_Anmeldung`, "
		f"`LVA Termine`, `Curricula`, `Ziele der Lehrveranstaltung`, `Lernergebnisse`) "
		f"VALUES ("
		f"'{page_fetch_lang}', '{course_number}', '{course_title}', '{semester}', "
		f"'{course_type}', '{course_sws}', '{course_ECTS}', '{additional_info}', "
		f"'{properties}', '{more_info}', '{subj_of_course}', '{methods}',"
		f"'{examination_mode}', '{exam_modalities}', '{course_reg}',"
		f"'{literatur}', '{prev_knowledge}', '{preced_courses}', '{lecturers}',"
		f"'{language}', '{institute}', '{groups_and_dates}', '{exams}',"
		f"'{group_reg}', '{course_dates}', '{curricula}', '{aim_of_course}',"
		f"'{learning_outcome}'"
		f");"
	)

	return sql
"""

if __name__ == "__main__":
	config = _load_config("config.yaml")
	log = logging.getLogger(__name__)
	logging.basicConfig(level=logging.INFO)

	semester = config["semester"]
	base     = config["output"]["base_dir"]
	data_dir = config["output"]["data_dir"]


	# --- courses ---
	filename_courses = Path(f"{base}{data_dir}courses_{semester}.json")
	dict_courses = state.load_state(str(filename_courses))

	output_sql = Path(f"{base}{data_dir}export_courses_{semester}.sql")
	export_courses(dict_courses, semester, output_sql)


	sys.exit()

	# --- Study programs ---
	filename_studyprograms = Path(f"{base}{data_dir}study_programs_{semester}.json")
	dict_studyprograms = state.load_state(str(filename_studyprograms))

	output_sql = Path(f"{base}{data_dir}export_overview_{semester}.sql")
	export_study_programs(dict_studyprograms, output_sql)
	print(f"Done. Import with:\n  mysql -u <user> -p <db> < {output_sql}")
