from bs4 import BeautifulSoup
from pathlib import Path
import sys
import yaml

import logging
import logger
import state

def _load_config(config_file: str) -> dict:
    with open(config_file) as f:
        return yaml.safe_load(f)


def _escape(value: str) -> str:
    """Escape single quotes for MySQL."""
    return value.replace("'", "\\'")


def _build_unique_id(entry: dict) -> str:
    return (
        entry["subsemester"]
        + entry["semester"]
        + entry["subprogram_title_de"]
        + entry["academic_program_de"]
    )


def export_study_programs(
    log: logging.Logger,
    dict_studyprograms: dict,
    output_path: Path
) -> None:
    lines = []
    lines.append("-- Study programs export")
    lines.append("-- Generated by export.py\n")

    for key, entry in dict_studyprograms.items():
        unique_id      = _escape(_build_unique_id(entry))
        course_numbers = _escape("|".join(entry.get("course_numbers", [])))
        semester       = _escape(entry.get("semester", ""))
        subsemester    = _escape(entry.get("subsemester", ""))
        subprogram_de  = _escape(entry.get("subprogram_title_de", ""))
        subprogram_en  = _escape(entry.get("subprogram_title_en", ""))
        academic_de    = _escape(entry.get("academic_program_de", ""))
        academic_en    = _escape(entry.get("academic_program_en", ""))
        program_code   = _escape(entry.get("program_code", ""))

        sql = (
            f"INSERT IGNORE INTO `overview` "
            f"(`unique_id`, `course_numbers`, `semester`, `subsemester`, "
            f"`subprogram_title_de`, `subprogram_title_en`, "
            f"`academic_program_de`, `academic_program_en`, `program_code`) "
            f"VALUES ("
            f"'{unique_id}', '{course_numbers}', '{semester}', '{subsemester}', "
            f"'{subprogram_de}', '{subprogram_en}', "
            f"'{academic_de}', '{academic_en}', '{program_code}'"
            f");"
        )
        lines.append(sql)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    log.info(
        f"Wrote {len(dict_studyprograms)} rows to {output_path}"
    )


# Map lang -> {field_name: json_key}
# extracted data has both german (de) and english (en) values as keys. The
# database column keys are fix -> select the proper keys depending on the
# crawled languages (as set below)!
_FIELD_KEYS = {
    "en": {
        "properties":       "properties",
        "more_info":        "additional information",
        "subj_of_course":   "subject of course",
        "methods":          "teaching methods",
        "exam_mode":        "mode of examination",
        "exam_modalities":  "examination modalities",
        "course_reg":       "course registration",
        "literatur":        "literature",
        "prev_knowledge":   "previous knowledge",
        "preced_courses":   "preceding courses",
        "lecturers":        "lecturers",
        "language":         "language",
        "institute":        "institute",
        "group_dates":      "groups and dates",
        "exams":            "exams",
        "group_reg":        "group registration",
        "course_dates":     "course dates",
        "curricula":        "curricula",
        "aim_of_course":    "aim of course",
        "learning_outcome": "learning outcomes",
    },
    "de": {
        "properties":       "merkmale",
        "more_info":        "weitere informationen",
        "subj_of_course":   "inhalt der lehrveranstaltung",
        "methods":          "methoden",
        "exam_mode":        "prüfungsmodus",
        "exam_modalities":  "leistungsnachweis",
        "course_reg":       "lva-anmeldung",
        "literatur":        "literatur",
        "prev_knowledge":   "vorkenntnisse",
        "preced_courses":   "vorausgehende lehrveranstaltungen",
        "lecturers":        "vortragende personen",
        "language":         "sprache",
        "institute":        "institut",
        "group_dates":      "gruppentermine",
        "exams":            "prüfungen",
        "group_reg":        "gruppen-anmeldung",
        "course_dates":     "lva termine",
        "curricula":        "curricula",
        "aim_of_course":    "ziele der lehrveranstaltung",
        "learning_outcome": "lernergebnisse",
    },
}


def _extract_lecturers(html: str) -> str:
    """
    Extract the lecturers for a course.
    """
    if not html:
        return ""
    soup = BeautifulSoup(html, "html.parser")
    names = [a.get_text(strip=True) for a in soup.find_all("a")]
    return "|".join(n for n in names if n)


def _extract_curricula(html: str) -> list:
    """
    Given the curricula requirements for a course. Extracts the
    curricula, formats and returns the values.
    """
    if not html:
        return []
    soup = BeautifulSoup(html, "html.parser")
    result = []
    for row in soup.select("tbody tr"):
        cells = row.find_all("td")
        if not cells:
            continue
        study_code = cells[0].get_text(strip=True)
        # semester, precon, info — columns 2,3,4 (index 1,2,3)
        extra = []
        for i in range(1, 4):
            if i < len(cells):
                text = cells[i].get_text(strip=True)
                # flag STEOP
                if i == 3 and ("STEOP" in str(cells[i]) or "Studieneingangs" in str(cells[i])):
                    text = "STEOP"
                extra.append(text)
            else:
                extra.append("")
        result.append(study_code)
        result.append(extra)
    return result


def _courses_process_lang(
    entry: dict,
    page_fetch_lang: str,
    table_name: str
) -> tuple[dict, int, str]:
    """
    Indices for de/en language dicts differ! -> select using "page_fetch_lang"
    """
    lang_entry = entry[page_fetch_lang]
    keys = _FIELD_KEYS[page_fetch_lang]

    non_empty_count = 0
    def get(field):
        nonlocal non_empty_count
        value = lang_entry.get(keys[field]) or ""
        if value:
            non_empty_count += 1
        return value

    course_number    = _escape(lang_entry.get("course_number", ""))
    course_title     = _escape(lang_entry.get("course_title", ""))
    semester         = _escape(lang_entry.get("course_semester", ""))
    course_type      = _escape(lang_entry.get("course_type", ""))
    course_sws       = _escape(lang_entry.get("course_hours", ""))
    course_ECTS      = _escape(lang_entry.get("course_ECTS", ""))
    additional_info  = _escape(lang_entry.get("course_add_info", "") or "")

    properties       = _escape(get("properties"))
    more_info        = _escape(get("more_info"))
    subj_of_course   = _escape(get("subj_of_course"))
    methods          = _escape(get("methods"))
    examination_mode = _escape(get("exam_mode"))
    exam_modalities  = _escape(get("exam_modalities"))
    course_reg       = _escape(get("course_reg"))
    literatur        = _escape(get("literatur"))
    prev_knowledge   = _escape(get("prev_knowledge"))
    preced_courses   = _escape(get("preced_courses"))
    lecturers        = _escape(_extract_lecturers(get("lecturers")))
    language         = _escape(get("language"))
    institute        = _escape(get("institute"))
    group_dates      = _escape(get("group_dates"))
    exams            = _escape(get("exams"))
    group_reg        = _escape(get("group_reg"))
    course_dates     = _escape(get("course_dates"))
    curricula        = _escape(str(_extract_curricula(get("curricula"))))
    aim_of_course    = _escape(get("aim_of_course"))
    learning_outcome = _escape(get("learning_outcome"))

    sql = (
        f"INSERT IGNORE INTO `{table_name}` "
        f"(`page_fetch_lang`, `course number`, `course title`, "
        f"`semester`, `type`, `sws`, `ECTS`, `add_info`, "
        f"`Merkmale`, `Weitere Informationen`, `Inhalt der Lehrveranstaltung`, "
        f"`Methoden`, `Prüfungsmodus`, `Leistungsnachweis`, `LVA_Anmeldung`, `Literatur`, "
        f"`Vorkenntnisse`, `Vorausgehende Lehrveranstaltungen`, `Vortragende Personen`, "
        f"`Sprache`, `Institut`, `Gruppentermine`, `Prüfungen`, `Gruppen_Anmeldung`, "
        f"`LVA Termine`, `Curricula`, `Ziele der Lehrveranstaltung`, `Lernergebnisse`) "
        f"VALUES ("
        f"'{page_fetch_lang}', '{course_number}', '{course_title}', '{semester}', "
        f"'{course_type}', '{course_sws}', '{course_ECTS}', '{additional_info}', "
        f"'{properties}', '{more_info}', '{subj_of_course}', '{methods}',"
        f"'{examination_mode}', '{exam_modalities}', '{course_reg}',"
        f"'{literatur}', '{prev_knowledge}', '{preced_courses}', '{lecturers}',"
        f"'{language}', '{institute}', '{group_dates}', '{exams}',"
        f"'{group_reg}', '{course_dates}', '{curricula}', '{aim_of_course}',"
        f"'{learning_outcome}'"
        f");"
    )

    return lang_entry, non_empty_count, sql


def export_courses(
    log: logging.Logger,
    dict_courses: dict,
    table_name  : str,
    output_path : Path
) -> None:
    lines = []
    lines.append("-- Courses export")
    lines.append("-- Generated by export.py\n")
    lines.append(
        f"CREATE TABLE IF NOT EXISTS `{table_name}` (\n"
        f"    `id_courses`                        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,\n"
        f"    `page_fetch_lang`                   VARCHAR(2)    NOT NULL,\n"
        f"    `course number`                     VARCHAR(7)   NOT NULL,\n"
        f"    `course title`                      TEXT,\n"
        f"    `semester`                          VARCHAR(5),\n"
        f"    `type`                              VARCHAR(2),\n"
        f"    `sws`                               VARCHAR(5),\n"
        f"    `ECTS`                              VARCHAR(6),\n"
        f"    `add_info`                          TEXT,\n"
        f"    `Merkmale`                          TEXT,\n"
        f"    `Weitere Informationen`             TEXT,\n"
        f"    `Inhalt der Lehrveranstaltung`      TEXT,\n"
        f"    `Methoden`                          TEXT,\n"
        f"    `Prüfungsmodus`                     TEXT,\n"
        f"    `Leistungsnachweis`                 TEXT,\n"
        f"    `LVA_Anmeldung`                     TEXT,\n"
        f"    `Literatur`                         TEXT,\n"
        f"    `Vorkenntnisse`                     TEXT,\n"
        f"    `Vorausgehende Lehrveranstaltungen` TEXT,\n"
        f"    `Vortragende Personen`              TEXT,\n"
        f"    `Sprache`                           VARCHAR(100),\n"
        f"    `Institut`                          TEXT,\n"
        f"    `Gruppentermine`                    TEXT,\n"
        f"    `Prüfungen`                         TEXT,\n"
        f"    `Gruppen_Anmeldung`                 TEXT,\n"
        f"    `LVA Termine`                       TEXT,\n"
        f"    `Curricula`                         TEXT,\n"
        f"    `Ziele der Lehrveranstaltung`       TEXT,\n"
        f"    `Lernergebnisse`                    TEXT,\n"
        f"    UNIQUE KEY `uq_course_lang` (`course number`, `page_fetch_lang`)\n"
        f") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n"
    )

    for course_number, entry in dict_courses.items():
        # make sure both languages properly extracted
        if "en" not in entry or "de" not in entry:
            log.error(f"missing language (de/en) in course '{course_number}'")
            continue

        # process german language of dict
        page_fetch_lang  = "de"
        lang_entry_de, non_empty_count_de, sql_de = _courses_process_lang(entry, page_fetch_lang, table_name)

        # process english language of dict
        page_fetch_lang  = "en"
        lang_entry_en, non_empty_count_en, sql_en = _courses_process_lang(entry, page_fetch_lang, table_name)

        # amount of "en" and "de" non-emmpty values should be the same.
        if non_empty_count_de != non_empty_count_en:
            # figure out which fields are causing the mismatch
            de_present = {f for f in _FIELD_KEYS["de"] if (lang_entry_de.get(_FIELD_KEYS["de"][f]) or "")}
            en_present = {f for f in _FIELD_KEYS["en"] if (lang_entry_en.get(_FIELD_KEYS["en"][f]) or "")}
            log.warning(
                f"Field mismatch {non_empty_count_de}/{non_empty_count_en} for {course_number}: "
                f"only in DE: {de_present - en_present}, "
                f"only in EN: {en_present - de_present}"
            )

        lines.append(sql_en)
        lines.append(sql_de)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    log.info(
        f"Wrote {len(dict_courses) * 2} rows "
        f"({len(dict_courses)} courses) to {output_path}"
    )


if __name__ == "__main__":
    config = _load_config("config.yaml")

    logger.setup_logger(config["logging"]["level"], config["logging"]["file"])  # set up logging
    log = logging.getLogger(__name__)

    semester = config["semester"]
    base     = config["output"]["base_dir"]
    data_dir = config["output"]["data_dir"]

    # --- courses ---
    filename_courses = Path(f"{base}{data_dir}courses_{semester}.json")
    dict_courses = state.load_state(str(filename_courses))

    output_sql = Path(f"{base}{data_dir}export_courses_{semester}.sql")
    export_courses(log, dict_courses, semester, output_sql)

    # --- Study programs ---
    filename_studyprograms = Path(f"{base}{data_dir}study_programs_{semester}.json")
    dict_studyprograms = state.load_state(str(filename_studyprograms))

    output_sql = Path(f"{base}{data_dir}export_overview_{semester}.sql")
    export_study_programs(log, dict_studyprograms, output_sql)
    print(f"Done. Import with:\n  mysql -u <user> -p <db> < {output_sql}")
